name: Auto-Tag & publish

on:
  push:
    branches: [az]

# Grant permissions for creating and pushing tags
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Need full history for tags

      - name: Calc Version, Tag & Push
        id: version_tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 --match '0.19.*')
          NEXT_PATCH=$(echo "$LATEST_TAG" | awk -F. '{ print $3+1 }')
          NEXT_VERSION="0.19.${NEXT_PATCH}"

          # Set the calculated version as a step output
          echo "next_version=$NEXT_VERSION" >> $GITHUB_OUTPUT

          git tag "$NEXT_VERSION"
          git push origin "$NEXT_VERSION"
        shell: bash

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Publish Artifact
        run: |
          (cd cftlib; ./gradlew -is publishToAzureArtifacts)
        env:
          AZURE_DEVOPS_ARTIFACT_USERNAME: ${{ secrets.AZURE_DEVOPS_ARTIFACT_USERNAME }}
          AZURE_DEVOPS_ARTIFACT_TOKEN: ${{ secrets.AZURE_DEVOPS_ARTIFACT_TOKEN }}
          RELEASE_VERSION: ${{ steps.version_tag.outputs.next_version }}
        shell: bash