name: Build

on:
  push:
  pull_request:
    branches:
      - main
jobs:
  spring-boot-2:
    name: SpringBoot2
    uses: ./.github/workflows/check.yml
    with:
      test_spring_boot_version: 2.6.10
  spring-boot-3:
    name: SpringBoot3
    uses: ./.github/workflows/check.yml
    with:
      test_spring_boot_version: 3.2.1
